// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/callegarimattia/battleship/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// GameService is an autogenerated mock type for the GameService type
type GameService struct {
	mock.Mock
}

// Attack provides a mock function with given fields: ctx, matchID, playerID, x, y
func (_m *GameService) Attack(ctx context.Context, matchID string, playerID string, x int, y int) (dto.GameView, error) {
	ret := _m.Called(ctx, matchID, playerID, x, y)

	if len(ret) == 0 {
		panic("no return value specified for Attack")
	}

	var r0 dto.GameView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) (dto.GameView, error)); ok {
		return rf(ctx, matchID, playerID, x, y)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) dto.GameView); ok {
		r0 = rf(ctx, matchID, playerID, x, y)
	} else {
		r0 = ret.Get(0).(dto.GameView)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int) error); ok {
		r1 = rf(ctx, matchID, playerID, x, y)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetState provides a mock function with given fields: ctx, matchID, playerID
func (_m *GameService) GetState(ctx context.Context, matchID string, playerID string) (dto.GameView, error) {
	ret := _m.Called(ctx, matchID, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetState")
	}

	var r0 dto.GameView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (dto.GameView, error)); ok {
		return rf(ctx, matchID, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) dto.GameView); ok {
		r0 = rf(ctx, matchID, playerID)
	} else {
		r0 = ret.Get(0).(dto.GameView)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, matchID, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaceShip provides a mock function with given fields: ctx, matchID, playerID, shipID, x, y, vertical
func (_m *GameService) PlaceShip(ctx context.Context, matchID string, playerID string, shipID int, x int, y int, vertical bool) (dto.GameView, error) {
	ret := _m.Called(ctx, matchID, playerID, shipID, x, y, vertical)

	if len(ret) == 0 {
		panic("no return value specified for PlaceShip")
	}

	var r0 dto.GameView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int, int, bool) (dto.GameView, error)); ok {
		return rf(ctx, matchID, playerID, shipID, x, y, vertical)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int, int, bool) dto.GameView); ok {
		r0 = rf(ctx, matchID, playerID, shipID, x, y, vertical)
	} else {
		r0 = ret.Get(0).(dto.GameView)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int, int, bool) error); ok {
		r1 = rf(ctx, matchID, playerID, shipID, x, y, vertical)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGameService creates a new instance of GameService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGameService(t interface {
	mock.TestingT
	Cleanup(func())
}) *GameService {
	mock := &GameService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
