// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/callegarimattia/battleship/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// IdentityService is an autogenerated mock type for the IdentityService type
type IdentityService struct {
	mock.Mock
}

// LoginOrRegister provides a mock function with given fields: ctx, username, source, extID
func (_m *IdentityService) LoginOrRegister(ctx context.Context, username string, source string, extID string) (dto.User, error) {
	ret := _m.Called(ctx, username, source, extID)

	if len(ret) == 0 {
		panic("no return value specified for LoginOrRegister")
	}

	var r0 dto.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (dto.User, error)); ok {
		return rf(ctx, username, source, extID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) dto.User); ok {
		r0 = rf(ctx, username, source, extID)
	} else {
		r0 = ret.Get(0).(dto.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, username, source, extID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIdentityService creates a new instance of IdentityService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentityService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdentityService {
	mock := &IdentityService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
