// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/callegarimattia/battleship/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// LobbyService is an autogenerated mock type for the LobbyService type
type LobbyService struct {
	mock.Mock
}

// CreateMatch provides a mock function with given fields: ctx, hostID
func (_m *LobbyService) CreateMatch(ctx context.Context, hostID string) (string, error) {
	ret := _m.Called(ctx, hostID)

	if len(ret) == 0 {
		panic("no return value specified for CreateMatch")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, hostID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, hostID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hostID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JoinMatch provides a mock function with given fields: ctx, matchID, playerID
func (_m *LobbyService) JoinMatch(ctx context.Context, matchID string, playerID string) (dto.GameView, error) {
	ret := _m.Called(ctx, matchID, playerID)

	if len(ret) == 0 {
		panic("no return value specified for JoinMatch")
	}

	var r0 dto.GameView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (dto.GameView, error)); ok {
		return rf(ctx, matchID, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) dto.GameView); ok {
		r0 = rf(ctx, matchID, playerID)
	} else {
		r0 = ret.Get(0).(dto.GameView)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, matchID, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListMatches provides a mock function with given fields: ctx
func (_m *LobbyService) ListMatches(ctx context.Context) ([]dto.MatchSummary, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListMatches")
	}

	var r0 []dto.MatchSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]dto.MatchSummary, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []dto.MatchSummary); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.MatchSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLobbyService creates a new instance of LobbyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLobbyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LobbyService {
	mock := &LobbyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
