all: true
dir: 'internal/mocks'
template: testify
filename: '{{.SrcPackageName}}/{{.InterfaceName}}.go'
pkgname: 'mock_{{.SrcPackageName}}'
packages:
  github.com/callegarimattia/battleship/internal/events:
  github.com/callegarimattia/battleship/internal/controller:
