// Code generated by "stringer -type=ShotResult,Orientation,GameState -output=model_string.go"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ShotResultInvalid-0]
	_ = x[ShotResultMiss-1]
	_ = x[ShotResultHit-2]
	_ = x[ShotResultSunk-3]
}

const _ShotResult_name = "ShotResultInvalidShotResultMissShotResultHitShotResultSunk"

var _ShotResult_index = [...]uint8{0, 17, 31, 44, 58}

func (i ShotResult) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ShotResult_index)-1 {
		return "ShotResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ShotResult_name[_ShotResult_index[idx]:_ShotResult_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Horizontal-0]
	_ = x[Vertical-1]
}

const _Orientation_name = "HorizontalVertical"

var _Orientation_index = [...]uint8{0, 10, 18}

func (i Orientation) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Orientation_index)-1 {
		return "Orientation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Orientation_name[_Orientation_index[idx]:_Orientation_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateWaiting-0]
	_ = x[StateSetup-1]
	_ = x[StatePlaying-2]
	_ = x[StateFinished-3]
}

const _GameState_name = "StateWaitingStateSetupStatePlayingStateFinished"

var _GameState_index = [...]uint8{0, 12, 22, 34, 47}

func (i GameState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_GameState_index)-1 {
		return "GameState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GameState_name[_GameState_index[idx]:_GameState_index[idx+1]]
}
