// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_controller

import (
	"context"

	"github.com/callegarimattia/battleship/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGameService creates a new instance of MockGameService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGameService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGameService {
	mock := &MockGameService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGameService is an autogenerated mock type for the GameService type
type MockGameService struct {
	mock.Mock
}

type MockGameService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGameService) EXPECT() *MockGameService_Expecter {
	return &MockGameService_Expecter{mock: &_m.Mock}
}

// Attack provides a mock function for the type MockGameService
func (_mock *MockGameService) Attack(ctx context.Context, matchID string, playerID string, x int, y int) (dto.GameView, error) {
	ret := _mock.Called(ctx, matchID, playerID, x, y)

	if len(ret) == 0 {
		panic("no return value specified for Attack")
	}

	var r0 dto.GameView
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, int) (dto.GameView, error)); ok {
		return returnFunc(ctx, matchID, playerID, x, y)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, int) dto.GameView); ok {
		r0 = returnFunc(ctx, matchID, playerID, x, y)
	} else {
		r0 = ret.Get(0).(dto.GameView)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int, int) error); ok {
		r1 = returnFunc(ctx, matchID, playerID, x, y)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameService_Attack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attack'
type MockGameService_Attack_Call struct {
	*mock.Call
}

// Attack is a helper method to define mock.On call
//   - ctx context.Context
//   - matchID string
//   - playerID string
//   - x int
//   - y int
func (_e *MockGameService_Expecter) Attack(ctx interface{}, matchID interface{}, playerID interface{}, x interface{}, y interface{}) *MockGameService_Attack_Call {
	return &MockGameService_Attack_Call{Call: _e.mock.On("Attack", ctx, matchID, playerID, x, y)}
}

func (_c *MockGameService_Attack_Call) Run(run func(ctx context.Context, matchID string, playerID string, x int, y int)) *MockGameService_Attack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGameService_Attack_Call) Return(gameView dto.GameView, err error) *MockGameService_Attack_Call {
	_c.Call.Return(gameView, err)
	return _c
}

func (_c *MockGameService_Attack_Call) RunAndReturn(run func(ctx context.Context, matchID string, playerID string, x int, y int) (dto.GameView, error)) *MockGameService_Attack_Call {
	_c.Call.Return(run)
	return _c
}

// GetState provides a mock function for the type MockGameService
func (_mock *MockGameService) GetState(ctx context.Context, matchID string, playerID string) (dto.GameView, error) {
	ret := _mock.Called(ctx, matchID, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetState")
	}

	var r0 dto.GameView
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (dto.GameView, error)); ok {
		return returnFunc(ctx, matchID, playerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) dto.GameView); ok {
		r0 = returnFunc(ctx, matchID, playerID)
	} else {
		r0 = ret.Get(0).(dto.GameView)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, matchID, playerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameService_GetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetState'
type MockGameService_GetState_Call struct {
	*mock.Call
}

// GetState is a helper method to define mock.On call
//   - ctx context.Context
//   - matchID string
//   - playerID string
func (_e *MockGameService_Expecter) GetState(ctx interface{}, matchID interface{}, playerID interface{}) *MockGameService_GetState_Call {
	return &MockGameService_GetState_Call{Call: _e.mock.On("GetState", ctx, matchID, playerID)}
}

func (_c *MockGameService_GetState_Call) Run(run func(ctx context.Context, matchID string, playerID string)) *MockGameService_GetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGameService_GetState_Call) Return(gameView dto.GameView, err error) *MockGameService_GetState_Call {
	_c.Call.Return(gameView, err)
	return _c
}

func (_c *MockGameService_GetState_Call) RunAndReturn(run func(ctx context.Context, matchID string, playerID string) (dto.GameView, error)) *MockGameService_GetState_Call {
	_c.Call.Return(run)
	return _c
}

// PlaceShip provides a mock function for the type MockGameService
func (_mock *MockGameService) PlaceShip(ctx context.Context, matchID string, playerID string, shipID int, x int, y int, vertical bool) (dto.GameView, error) {
	ret := _mock.Called(ctx, matchID, playerID, shipID, x, y, vertical)

	if len(ret) == 0 {
		panic("no return value specified for PlaceShip")
	}

	var r0 dto.GameView
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, int, int, bool) (dto.GameView, error)); ok {
		return returnFunc(ctx, matchID, playerID, shipID, x, y, vertical)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, int, int, bool) dto.GameView); ok {
		r0 = returnFunc(ctx, matchID, playerID, shipID, x, y, vertical)
	} else {
		r0 = ret.Get(0).(dto.GameView)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int, int, int, bool) error); ok {
		r1 = returnFunc(ctx, matchID, playerID, shipID, x, y, vertical)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameService_PlaceShip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PlaceShip'
type MockGameService_PlaceShip_Call struct {
	*mock.Call
}

// PlaceShip is a helper method to define mock.On call
//   - ctx context.Context
//   - matchID string
//   - playerID string
//   - shipID int
//   - x int
//   - y int
//   - vertical bool
func (_e *MockGameService_Expecter) PlaceShip(ctx interface{}, matchID interface{}, playerID interface{}, shipID interface{}, x interface{}, y interface{}, vertical interface{}) *MockGameService_PlaceShip_Call {
	return &MockGameService_PlaceShip_Call{Call: _e.mock.On("PlaceShip", ctx, matchID, playerID, shipID, x, y, vertical)}
}

func (_c *MockGameService_PlaceShip_Call) Run(run func(ctx context.Context, matchID string, playerID string, shipID int, x int, y int, vertical bool)) *MockGameService_PlaceShip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		var arg6 bool
		if args[6] != nil {
			arg6 = args[6].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockGameService_PlaceShip_Call) Return(gameView dto.GameView, err error) *MockGameService_PlaceShip_Call {
	_c.Call.Return(gameView, err)
	return _c
}

func (_c *MockGameService_PlaceShip_Call) RunAndReturn(run func(ctx context.Context, matchID string, playerID string, shipID int, x int, y int, vertical bool) (dto.GameView, error)) *MockGameService_PlaceShip_Call {
	_c.Call.Return(run)
	return _c
}
