// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_controller

import (
	"context"

	"github.com/callegarimattia/battleship/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIdentityService creates a new instance of MockIdentityService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdentityService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdentityService {
	mock := &MockIdentityService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIdentityService is an autogenerated mock type for the IdentityService type
type MockIdentityService struct {
	mock.Mock
}

type MockIdentityService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdentityService) EXPECT() *MockIdentityService_Expecter {
	return &MockIdentityService_Expecter{mock: &_m.Mock}
}

// LoginOrRegister provides a mock function for the type MockIdentityService
func (_mock *MockIdentityService) LoginOrRegister(ctx context.Context, username string, source string, extID string) (dto.AuthResponse, error) {
	ret := _mock.Called(ctx, username, source, extID)

	if len(ret) == 0 {
		panic("no return value specified for LoginOrRegister")
	}

	var r0 dto.AuthResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (dto.AuthResponse, error)); ok {
		return returnFunc(ctx, username, source, extID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) dto.AuthResponse); ok {
		r0 = returnFunc(ctx, username, source, extID)
	} else {
		r0 = ret.Get(0).(dto.AuthResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, username, source, extID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIdentityService_LoginOrRegister_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginOrRegister'
type MockIdentityService_LoginOrRegister_Call struct {
	*mock.Call
}

// LoginOrRegister is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - source string
//   - extID string
func (_e *MockIdentityService_Expecter) LoginOrRegister(ctx interface{}, username interface{}, source interface{}, extID interface{}) *MockIdentityService_LoginOrRegister_Call {
	return &MockIdentityService_LoginOrRegister_Call{Call: _e.mock.On("LoginOrRegister", ctx, username, source, extID)}
}

func (_c *MockIdentityService_LoginOrRegister_Call) Run(run func(ctx context.Context, username string, source string, extID string)) *MockIdentityService_LoginOrRegister_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIdentityService_LoginOrRegister_Call) Return(authResponse dto.AuthResponse, err error) *MockIdentityService_LoginOrRegister_Call {
	_c.Call.Return(authResponse, err)
	return _c
}

func (_c *MockIdentityService_LoginOrRegister_Call) RunAndReturn(run func(ctx context.Context, username string, source string, extID string) (dto.AuthResponse, error)) *MockIdentityService_LoginOrRegister_Call {
	_c.Call.Return(run)
	return _c
}
