// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_controller

import (
	"context"

	"github.com/callegarimattia/battleship/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLobbyService creates a new instance of MockLobbyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLobbyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLobbyService {
	mock := &MockLobbyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLobbyService is an autogenerated mock type for the LobbyService type
type MockLobbyService struct {
	mock.Mock
}

type MockLobbyService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLobbyService) EXPECT() *MockLobbyService_Expecter {
	return &MockLobbyService_Expecter{mock: &_m.Mock}
}

// CreateMatch provides a mock function for the type MockLobbyService
func (_mock *MockLobbyService) CreateMatch(ctx context.Context, hostID string) (string, error) {
	ret := _mock.Called(ctx, hostID)

	if len(ret) == 0 {
		panic("no return value specified for CreateMatch")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, hostID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, hostID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hostID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLobbyService_CreateMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMatch'
type MockLobbyService_CreateMatch_Call struct {
	*mock.Call
}

// CreateMatch is a helper method to define mock.On call
//   - ctx context.Context
//   - hostID string
func (_e *MockLobbyService_Expecter) CreateMatch(ctx interface{}, hostID interface{}) *MockLobbyService_CreateMatch_Call {
	return &MockLobbyService_CreateMatch_Call{Call: _e.mock.On("CreateMatch", ctx, hostID)}
}

func (_c *MockLobbyService_CreateMatch_Call) Run(run func(ctx context.Context, hostID string)) *MockLobbyService_CreateMatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLobbyService_CreateMatch_Call) Return(s string, err error) *MockLobbyService_CreateMatch_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockLobbyService_CreateMatch_Call) RunAndReturn(run func(ctx context.Context, hostID string) (string, error)) *MockLobbyService_CreateMatch_Call {
	_c.Call.Return(run)
	return _c
}

// JoinMatch provides a mock function for the type MockLobbyService
func (_mock *MockLobbyService) JoinMatch(ctx context.Context, matchID string, playerID string) (dto.GameView, error) {
	ret := _mock.Called(ctx, matchID, playerID)

	if len(ret) == 0 {
		panic("no return value specified for JoinMatch")
	}

	var r0 dto.GameView
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (dto.GameView, error)); ok {
		return returnFunc(ctx, matchID, playerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) dto.GameView); ok {
		r0 = returnFunc(ctx, matchID, playerID)
	} else {
		r0 = ret.Get(0).(dto.GameView)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, matchID, playerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLobbyService_JoinMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinMatch'
type MockLobbyService_JoinMatch_Call struct {
	*mock.Call
}

// JoinMatch is a helper method to define mock.On call
//   - ctx context.Context
//   - matchID string
//   - playerID string
func (_e *MockLobbyService_Expecter) JoinMatch(ctx interface{}, matchID interface{}, playerID interface{}) *MockLobbyService_JoinMatch_Call {
	return &MockLobbyService_JoinMatch_Call{Call: _e.mock.On("JoinMatch", ctx, matchID, playerID)}
}

func (_c *MockLobbyService_JoinMatch_Call) Run(run func(ctx context.Context, matchID string, playerID string)) *MockLobbyService_JoinMatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLobbyService_JoinMatch_Call) Return(gameView dto.GameView, err error) *MockLobbyService_JoinMatch_Call {
	_c.Call.Return(gameView, err)
	return _c
}

func (_c *MockLobbyService_JoinMatch_Call) RunAndReturn(run func(ctx context.Context, matchID string, playerID string) (dto.GameView, error)) *MockLobbyService_JoinMatch_Call {
	_c.Call.Return(run)
	return _c
}

// ListMatches provides a mock function for the type MockLobbyService
func (_mock *MockLobbyService) ListMatches(ctx context.Context) ([]dto.MatchSummary, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListMatches")
	}

	var r0 []dto.MatchSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]dto.MatchSummary, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []dto.MatchSummary); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.MatchSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLobbyService_ListMatches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMatches'
type MockLobbyService_ListMatches_Call struct {
	*mock.Call
}

// ListMatches is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLobbyService_Expecter) ListMatches(ctx interface{}) *MockLobbyService_ListMatches_Call {
	return &MockLobbyService_ListMatches_Call{Call: _e.mock.On("ListMatches", ctx)}
}

func (_c *MockLobbyService_ListMatches_Call) Run(run func(ctx context.Context)) *MockLobbyService_ListMatches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLobbyService_ListMatches_Call) Return(matchSummarys []dto.MatchSummary, err error) *MockLobbyService_ListMatches_Call {
	_c.Call.Return(matchSummarys, err)
	return _c
}

func (_c *MockLobbyService_ListMatches_Call) RunAndReturn(run func(ctx context.Context) ([]dto.MatchSummary, error)) *MockLobbyService_ListMatches_Call {
	_c.Call.Return(run)
	return _c
}
