// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_controller

import (
	"github.com/callegarimattia/battleship/internal/controller"
	"github.com/callegarimattia/battleship/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotificationService creates a new instance of MockNotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationService {
	mock := &MockNotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationService is an autogenerated mock type for the NotificationService type
type MockNotificationService struct {
	mock.Mock
}

type MockNotificationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationService) EXPECT() *MockNotificationService_Expecter {
	return &MockNotificationService_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockNotificationService
func (_mock *MockNotificationService) Publish(event *dto.GameEvent) {
	_mock.Called(event)
	return
}

// MockNotificationService_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockNotificationService_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - event *dto.GameEvent
func (_e *MockNotificationService_Expecter) Publish(event interface{}) *MockNotificationService_Publish_Call {
	return &MockNotificationService_Publish_Call{Call: _e.mock.On("Publish", event)}
}

func (_c *MockNotificationService_Publish_Call) Run(run func(event *dto.GameEvent)) *MockNotificationService_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *dto.GameEvent
		if args[0] != nil {
			arg0 = args[0].(*dto.GameEvent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNotificationService_Publish_Call) Return() *MockNotificationService_Publish_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotificationService_Publish_Call) RunAndReturn(run func(event *dto.GameEvent)) *MockNotificationService_Publish_Call {
	_c.Run(run)
	return _c
}

// Subscribe provides a mock function for the type MockNotificationService
func (_mock *MockNotificationService) Subscribe(matchID string) (controller.Subscription, <-chan *dto.GameEvent) {
	ret := _mock.Called(matchID)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 controller.Subscription
	var r1 <-chan *dto.GameEvent
	if returnFunc, ok := ret.Get(0).(func(string) (controller.Subscription, <-chan *dto.GameEvent)); ok {
		return returnFunc(matchID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) controller.Subscription); ok {
		r0 = returnFunc(matchID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(controller.Subscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) <-chan *dto.GameEvent); ok {
		r1 = returnFunc(matchID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan *dto.GameEvent)
		}
	}
	return r0, r1
}

// MockNotificationService_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockNotificationService_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - matchID string
func (_e *MockNotificationService_Expecter) Subscribe(matchID interface{}) *MockNotificationService_Subscribe_Call {
	return &MockNotificationService_Subscribe_Call{Call: _e.mock.On("Subscribe", matchID)}
}

func (_c *MockNotificationService_Subscribe_Call) Run(run func(matchID string)) *MockNotificationService_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNotificationService_Subscribe_Call) Return(subscription controller.Subscription, gameEventCh <-chan *dto.GameEvent) *MockNotificationService_Subscribe_Call {
	_c.Call.Return(subscription, gameEventCh)
	return _c
}

func (_c *MockNotificationService_Subscribe_Call) RunAndReturn(run func(matchID string) (controller.Subscription, <-chan *dto.GameEvent)) *MockNotificationService_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
