// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_events

import (
	"github.com/callegarimattia/battleship/internal/events"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventBus creates a new instance of MockEventBus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventBus(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventBus {
	mock := &MockEventBus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventBus is an autogenerated mock type for the EventBus type
type MockEventBus struct {
	mock.Mock
}

type MockEventBus_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventBus) EXPECT() *MockEventBus_Expecter {
	return &MockEventBus_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockEventBus
func (_mock *MockEventBus) Close() {
	_mock.Called()
	return
}

// MockEventBus_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockEventBus_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockEventBus_Expecter) Close() *MockEventBus_Close_Call {
	return &MockEventBus_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockEventBus_Close_Call) Run(run func()) *MockEventBus_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventBus_Close_Call) Return() *MockEventBus_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventBus_Close_Call) RunAndReturn(run func()) *MockEventBus_Close_Call {
	_c.Run(run)
	return _c
}

// Publish provides a mock function for the type MockEventBus
func (_mock *MockEventBus) Publish(event *events.GameEvent) {
	_mock.Called(event)
	return
}

// MockEventBus_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockEventBus_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - event *events.GameEvent
func (_e *MockEventBus_Expecter) Publish(event interface{}) *MockEventBus_Publish_Call {
	return &MockEventBus_Publish_Call{Call: _e.mock.On("Publish", event)}
}

func (_c *MockEventBus_Publish_Call) Run(run func(event *events.GameEvent)) *MockEventBus_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *events.GameEvent
		if args[0] != nil {
			arg0 = args[0].(*events.GameEvent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventBus_Publish_Call) Return() *MockEventBus_Publish_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventBus_Publish_Call) RunAndReturn(run func(event *events.GameEvent)) *MockEventBus_Publish_Call {
	_c.Run(run)
	return _c
}

// Subscribe provides a mock function for the type MockEventBus
func (_mock *MockEventBus) Subscribe(matchID string, handler events.EventHandler) events.Subscription {
	ret := _mock.Called(matchID, handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 events.Subscription
	if returnFunc, ok := ret.Get(0).(func(string, events.EventHandler) events.Subscription); ok {
		r0 = returnFunc(matchID, handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(events.Subscription)
		}
	}
	return r0
}

// MockEventBus_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockEventBus_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - matchID string
//   - handler events.EventHandler
func (_e *MockEventBus_Expecter) Subscribe(matchID interface{}, handler interface{}) *MockEventBus_Subscribe_Call {
	return &MockEventBus_Subscribe_Call{Call: _e.mock.On("Subscribe", matchID, handler)}
}

func (_c *MockEventBus_Subscribe_Call) Run(run func(matchID string, handler events.EventHandler)) *MockEventBus_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 events.EventHandler
		if args[1] != nil {
			arg1 = args[1].(events.EventHandler)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventBus_Subscribe_Call) Return(subscription events.Subscription) *MockEventBus_Subscribe_Call {
	_c.Call.Return(subscription)
	return _c
}

func (_c *MockEventBus_Subscribe_Call) RunAndReturn(run func(matchID string, handler events.EventHandler) events.Subscription) *MockEventBus_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
