// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock_events

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSubscription creates a new instance of MockSubscription. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscription(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscription {
	mock := &MockSubscription{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubscription is an autogenerated mock type for the Subscription type
type MockSubscription struct {
	mock.Mock
}

type MockSubscription_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscription) EXPECT() *MockSubscription_Expecter {
	return &MockSubscription_Expecter{mock: &_m.Mock}
}

// Unsubscribe provides a mock function for the type MockSubscription
func (_mock *MockSubscription) Unsubscribe() {
	_mock.Called()
	return
}

// MockSubscription_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MockSubscription_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
func (_e *MockSubscription_Expecter) Unsubscribe() *MockSubscription_Unsubscribe_Call {
	return &MockSubscription_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe")}
}

func (_c *MockSubscription_Unsubscribe_Call) Run(run func()) *MockSubscription_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSubscription_Unsubscribe_Call) Return() *MockSubscription_Unsubscribe_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSubscription_Unsubscribe_Call) RunAndReturn(run func()) *MockSubscription_Unsubscribe_Call {
	_c.Run(run)
	return _c
}
